---
all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: "{{ lookup('env', 'PROXMOX_VE_HOSTNAME') }}"
          ansible_user: "{{ lookup('env', 'PROXMOX_VM_SSH_USERNAME') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_PRIVATE_KEY_FILE') }}"
