---
all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: "{{ lookup('env', 'PVE_HOST') }}"
          ansible_user: "{{ lookup('env', 'PVE_USER') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_PRIVATE_KEY_FILE') }}"
