---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

driver:
  name: docker

platforms:
  - name: proxmox-test
    image: debian:12
    pre_build_image: true
    privileged: true
    command: /bin/bash -c "while true; do sleep 1000; done"
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      gathering: smart
  inventory:
    group_vars:
      all:
        ansible_connection: docker
        # Override defaults for testing environment
        zfs_swap_size: "1G"
        common_packages:
          - htop

verifier:
  name: ansible
