---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Python (required for Ansible)
      ansible.builtin.raw: |
        apt-get update && apt-get install -y python3
      changed_when: true
