---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Verify sysctl configuration file exists
      ansible.builtin.stat:
        path: /etc/sysctl.d/10-proxmox-tuning.conf
      register: sysctl_file
      failed_when: not sysctl_file.stat.exists

    - name: Verify ulimits configuration file exists
      ansible.builtin.stat:
        path: /etc/security/limits.d/90-ansible.conf
      register: limits_file
      failed_when: not limits_file.stat.exists

    - name: Verify systemd limits directory exists
      ansible.builtin.stat:
        path: /etc/systemd/system.conf.d
      register: systemd_dir
      failed_when: not systemd_dir.stat.exists

    - name: Verify systemd limits configuration exists
      ansible.builtin.stat:
        path: /etc/systemd/system.conf.d/limits.conf
      register: systemd_limits
      failed_when: not systemd_limits.stat.exists
