---
- name: Verify
  hosts: all
  # Note: become: false since Docker containers run as root
  become: false
  gather_facts: true

  tasks:
    - name: Verify sysctl configuration file exists
      ansible.builtin.stat:
        path: /etc/sysctl.d/10-proxmox-tuning.conf
      register: sysctl_file
      failed_when: not sysctl_file.stat.exists

    - name: Verify ulimits configuration file exists
      ansible.builtin.stat:
        path: /etc/security/limits.d/90-ansible.conf
      register: limits_file
      failed_when: not limits_file.stat.exists

    - name: Verify systemd limits directory exists
      ansible.builtin.stat:
        path: /etc/systemd/system.conf.d
      register: systemd_dir
      failed_when: not systemd_dir.stat.exists

    - name: Verify systemd limits configuration exists
      ansible.builtin.stat:
        path: /etc/systemd/system.conf.d/limits.conf
      register: systemd_limits
      failed_when: not systemd_limits.stat.exists

    - name: Verify /etc/kernel/cmdline exists (if boot params enabled)
      ansible.builtin.stat:
        path: /etc/kernel/cmdline
      register: kernel_cmdline_file
      # This is only expected to exist on actual Proxmox systems, not in molecule Docker containers
      failed_when: false
      changed_when: false

    - name: Display kernel cmdline content if it exists
      ansible.builtin.debug:
        msg: "Kernel cmdline found (requires Proxmox): {{ kernel_cmdline_file.stat.exists }}"
      changed_when: false
